// client/Angular/src/app/addbar/addbar.component.ts
import { Component, OnInit,Input, Output, EventEmitter } from '@angular/core';
import { Movie } from '../movie';
import { MovieService } from '../movie.service';

@Component({
  selector: 'app-addbar',
  templateUrl: './addbar.component.html',
  styleUrls: ['./addbar.component.css']
})
export class AddbarComponent implements OnInit {

  addMovie: boolean= false;
  updateMovie: boolean= false;
  categories: string[] = ["Action", "Science Fiction", "Suspense", "Comedy", "Drama"];
  warn: string= "";
  newMovie: Movie={
    name: "",
    category: "",
    grade: 0,
    imgurl: "",
  };
  clicked: boolean= false;

  constructor() { }

  ngOnInit(): void {
  }

  @Input () names: string[] = [];
  @Input () movies: Movie[] = [];
  @Output() movieToAdd = new EventEmitter<Movie>();
  @Output() movieToUpdate = new EventEmitter<Movie>();

  setMovie(value: Movie){
      let check= Object.values(this.newMovie).some(x => x === null || x === '');
      if (check) {
        this.warn="Fill in all the details"
      }
      else if (this.newMovie.grade<1 || this.newMovie.grade>10){
        this.warn="Fill a grade between 1 and 10"}
      else
      {this.movieToAdd.emit(value);
        this.close("add");
      }
      
  } 
  
  setToUpdate(value: Movie){
      this.movieToUpdate.emit(value);
      this.close("update");
} 

  fill(name: string)
  {let index = this.movies.findIndex((x)=>x.name===name);
    this.newMovie=this.movies[index]
  }

  close(action: string){
    action==="add"?this.addMovie=false:this.updateMovie=false;
    this.warn='';
    this.newMovie={
      name: "",
      category: "",
      grade: 0,
      imgurl: "",
    };
    this.clicked=false
  }
  
}

<div>
    <!-- <iframe src="https://www.youtube.com/embed?v=cxEa5ChEK9E&list=RDcxEa5ChEK9E&start_radio=1"></iframe> -->
    <div class="buttons" *ngIf="!addMovie && !updateMovie">
        <button class="up-button" (click)="addMovie=true; clicked=true">Add movie</button>
        <button class="up-button" (click)="updateMovie=true; clicked=true">Update movie</button>
    </div>
    <div>{{newMovie.name}}</div>
    <div class="add" *ngIf="addMovie">
        <h2>ADD MOVIE</h2>
            <mat-form-field appearance="fill">
                <mat-label>Name</mat-label>
                <input matInput placeholder="Name" [(ngModel)]="newMovie.name">
            </mat-form-field>
            <mat-form-field appearance="fill">
            <mat-label>Category</mat-label>
            <mat-select>
                <mat-option *ngFor="let category of categories" value="category" (click)="newMovie.category=category">
                {{category}}
                </mat-option>
            </mat-select>
            </mat-form-field>
            <mat-form-field appearance="fill">
                <mat-label>Grade</mat-label>
                <input matInput type="number" min="1" max="10"  placeholder="Grade" [(ngModel)]="newMovie.grade">
            </mat-form-field>
            <mat-form-field appearance="fill">
                <mat-label>Image URL</mat-label>
                <input matInput placeholder="Image URL" [(ngModel)]="newMovie.imgurl">
            </mat-form-field>
            <div class="down-buttons">
                <button class="down-button" (click)="setMovie(newMovie)" >Add</button>
                <button class="down-button" (click)="close('add')">Close</button>
            </div>
            <div class="warn" >{{warn}}</div>
    </div>

    <div class="update" *ngIf="updateMovie">
        <H2>UPDATE MOVIE</H2>
        <mat-form-field appearance="fill">
            <mat-label>Name</mat-label>
            <mat-select>
                <mat-option *ngFor="let name of names" value="name" (click)="fill(name)">
                {{name}}
                </mat-option>
            </mat-select>
            </mat-form-field>
            <mat-form-field appearance="fill">
            <mat-label>{{newMovie.category?newMovie.category: "Category"}}</mat-label>
            <mat-select>
                <mat-option *ngFor="let category of categories" value="category" (click)="newMovie.category=category">
                {{category}}
                </mat-option>
            </mat-select>
            </mat-form-field>
            <mat-form-field appearance="fill">
                <mat-label>Grade</mat-label>
                <input matInput type="number" min="1" max="10"  placeholder="Grade" [(ngModel)]="newMovie.grade">
            </mat-form-field>
            <mat-form-field appearance="fill">
                <mat-label>Image URL</mat-label>
                <input matInput placeholder="Image URL" [(ngModel)]="newMovie.imgurl">
            </mat-form-field>
            <div class="down-buttons">
                <button class="down-button" (click)="setToUpdate(newMovie)" >Update</button>
                <button class="down-button" (click)="close('update')">Close</button>
            </div>    
    </div>
    <div *ngIf="!clicked" class="app-logo-div" >
        <img class="App-logo-search-bar " src="../../assets/imgmovie.svg" className="App-logo-add-bar" alt="logo" />
    </div>
</div>

// client/React/src/components/addbar/addbar.js
import "./addbar.css"
import { Form, Button, DropdownButton, Dropdown} from 'react-bootstrap';
import React, { useState, useRef} from "react";
import axios from "axios";
import ReactPlayer from 'react-player';

function Bar({movies, setMovies , names,setNames}){
    const [showAdd,setShowAdd] = useState(false)
    const [showUpdate,setShowUpdate] = useState(false)
    const [Name,setName] = useState();
    const [Category,setCategory] = useState();
    const [Grade,setGrade] = useState(0);
    const [ImageUrl,setImageUrl] = useState();
    const [lack,setLack] = useState(false);
    const [update,setUpdate] = useState({})
    const [err,setErr] = useState();    
    const [success,setSuccess] = useState();
    let server = process.env.REACT_APP_SERVER_ADDRESS;
    let categories = ["Action", "Science Fiction", "Suspense", "Comedy", "Drama"]

    const onclick=(e)=>{setCategory(e.target.text)};
    
    const toFill=(name)=>{
      setCategory();
      let theMovie=movies.find((m)=>m.name===name);
      setUpdate(theMovie)
    }

    function sendAdd(){
        let id=0;
        movies.forEach((e)=>{if(e.id>id){id=e.id}});

        if (Name && Category && Grade && ImageUrl){
          let obj={
            id:id+1,
            name:Name,
            category: Category,
            grade:Grade,
            imgurl: ImageUrl
          }
          // axios.post(server+"/Movies",obj)
          axios.post("http://localhost:8000/Movies/Add",obj)
          .then(res=>{
            setMovies(res.data);
            let theNames=[];
            res.data.forEach((m)=>theNames.push(m.name));  
            setNames(theNames);
            setErr();
            setSuccess("The movie was successfully added!");
          })
          .catch(err => {setErr(err.response.data)});
            setLack(false);
          }
        else {setLack(true)}
    }

    function sendUpdate(){
        let obj={
          id: update.id,
          // _id:update._id,
          name: update.name,
          category: Category? Category:update.category,
          grade: Grade? Grade:update.grade,
          imgurl: ImageUrl? ImageUrl:update.imgurl
        }
        // axios.put(server+"/Movies",obj)
        axios.put("http://localhost:8000/Movies/Update",obj)
        .then(res=>{    
          setMovies(res.data);
          let theNames = [];
          res.data.forEach((m)=>theNames.push(m.name));  
          setNames(theNames);
          setSuccess("The movie has been successfully updated!")
        })
  }

return(
    <div className="container">
      {/* <iframe src="https://www.youtube.com/embed?v=cxEa5ChEK9E&list=RDcxEa5ChEK9E&start_radio=1"></iframe>  */}
      {/* <ReactPlayer url="https://www.youtube.com/watch?v=ezs5QvWBtf4" controls={true}/> */}

      {!showAdd && !showUpdate &&
        <div style={{display:"flex", justifyContent:"space-between"}}>
          <Button variant="secondary" onClick={()=>setShowAdd(true)}>Add movie</Button>
          <Button variant="secondary" onClick={()=>setShowUpdate(true)}>Update movie</Button>
        </div>}

      {showAdd &&
       <Form>
          <h5>Add new movie</h5>

          <Form.Group>
            <Form.Control className="input" placeholder="Name"  onChange={(e)=>{setName(e.target.value);setErr()}}/>
          </Form.Group>

          <div style={{marginBottom: "15px",width:"100%"}}>
            <DropdownButton className="dropdown-basic-button add-buttun" title={!Category? "Category":Category}>
              {categories.map((category)=>
              <Dropdown.Item key={category} onClick={onclick}>{category}</Dropdown.Item>)}
            </DropdownButton>
          </div>

          <Form.Group>
            <Form.Control onChange={(e)=>setGrade(e.target.value)} className="input" placeholder="Grade" />
          </Form.Group>

          <Form.Group>
            <Form.Control onChange={(e)=>setImageUrl(e.target.value)} className="input" placeholder="Image Url" />
          </Form.Group>
      
          <div style={{display:"flex",justifyContent:"space-between"}}>
          <Button onClick={sendAdd}> Add </Button>
          <Button onClick={()=>{setShowAdd(false);setErr();setSuccess()}}> Close </Button>
          </div>

          {lack&&<div style={{color:"red"}}>Fill in all the details</div>}
          {err&&<div style={{color:"red"}}>{err}</div>}
          {success&&<div style={{backgroundColor:"white",color:"green"}}>{success}</div>}

        </Form>}

      {showUpdate&&
        <Form>
          <h5>Update movie</h5>
          <div>Select a movie by name</div>
          <div style={{marginBottom: "15px",width:"100%"}}>
            <DropdownButton className="dropdown-basic-button" title={!update.name? "Name":update.name}>
              {names.map((name)=>
              <Dropdown.Item key={name} onClick={(e)=>toFill(e.target.text)}>{name}</Dropdown.Item>)}            
            </DropdownButton>
          </div>
          
          <div style={{marginBottom: "15px",width:"100%"}}>
            <DropdownButton className="dropdown-basic-button" style={{width:"100% !important"}} title={!update.category?"Category":(!Category?update.category:Category)}>
              {categories.map((category)=>
              <Dropdown.Item key={category} onClick={onclick}>{category}</Dropdown.Item>)}           
            </DropdownButton> 
          </div>

          <Form.Group>
            <Form.Control onChange={(e)=>setGrade(e.target.value)} className="input" placeholder={!update.grade?"Grade":update.grade} />
          </Form.Group>

          <Form.Group>
            <Form.Control onChange={(e)=>setImageUrl(e.target.value)} className="input" placeholder={!update.imgurl?"Image Url":update.imgurl} />
          </Form.Group>
          <div style={{display:"flex",justifyContent:"space-between"}}>
          <Button onClick={sendUpdate}>
            Update
          </Button>

          <Button onClick={()=>{setShowUpdate(false);setUpdate({});setCategory();setGrade();setImageUrl();setSuccess()}}>
            Close
          </Button>
          </div>

        </Form>}

      {!showAdd&&!showUpdate&&
        <div className="app-logo-div">
        <img src="imgmovie.svg" className="App-logo-add-bar" alt="logo" />
        </div>}
    
    </div>
)


}

export default Bar;
