// client/React/src/components/searchbar/searchbar.js
import "./searchbar.css"
import { Dropdown, DropdownButton } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import React, {useState} from "react";

function Bar({setSearch}){

    const onclick=(e)=>{setSearch(e.target.text)}
    const [clicked,setClicked]=useState(false);
    let categories = ["Action", "Science Fiction", "Suspense", "Comedy", "Drama"]

return(
    <div className="divdropdown">
        
        <DropdownButton id="dropdown-basic-button" title="Select a category" onClick={()=>setClicked(!clicked)}>
            <Dropdown.Item onClick={()=>setSearch()} href="#/action-1">All movies</Dropdown.Item>
            {categories.map((category)=>
            <Dropdown.Item key={category} onClick={onclick}>{category}</Dropdown.Item>)}
        </DropdownButton>

        {!clicked &&
            <div className="app-logo-div">
                <img src="imgmovie.svg" className="App-logo-add-bar" alt="logo" />
            </div>}

    </div>
)
}

export default Bar;

// client/Angular/src/app/searchbar/searchbar.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-searchbar',
  templateUrl: './searchbar.component.html',
  styleUrls: ['./searchbar.component.css']
})
export class SearchbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
 
  @Output() search = new EventEmitter<string>();

  setSearch(value: string){
      this.search.emit(value);
  } 
  
  selected: string="";
  clicked:boolean = false;
  categories: string[] = ["Action", "Science Fiction", "Suspense", "Comedy", "Drama"]

}

<div class="divdropdown">
    <mat-form-field appearance="fill" (click)="clicked=true">
        <mat-label>Select a category</mat-label>
        <mat-select [(value)]="selected" (click)="clicked=!clicked">
        `<mat-option [value]="" (click)="setSearch(''); clicked=!clicked">
                All movies
        </mat-option>
          <mat-option *ngFor="let category of categories" [value]="category" (click)="setSearch(category);clicked=!clicked">
            {{category}}
          </mat-option>
        </mat-select>
      </mat-form-field>
  
    <div *ngIf="!clicked" class="app-logo-div" >
        <img class="App-logo-search-bar " src="../../assets/imgmovie.svg" className="App-logo-add-bar" alt="logo" />
    </div>

</div>
