// client/Angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from '../../environments/environment';
import { Movie } from '../movie';
import { MovieService } from '../movie.service';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  error = '';
  server=environment.server;
  name:string = "";
  movies:Movie[] = [];
  names:string[] = [];
  show:boolean = false;
  selectedCatgory: string="";

  constructor(private MovieService:MovieService) { }

  ngOnInit(): void {
    this.getMovies("")
  }
 
  getMovies(search:string): void {
    this.selectedCatgory=search;
    this.MovieService
    .getAll(search)
    .subscribe(
      (data: Movie[]) => {
        this.movies = data; 
        if(this.names.length<1)       
        {this.fillNames()};
      },
      (err) => {
        console.log(err)
        this.error = err.message;
      }
    );
  }

  addmovie(movie:Movie){
    console.log(movie)
    this.MovieService
    .add(movie)
    .subscribe(
      (data: Movie[]) => {
        this.movies = data;
        this.fillNames();
        console.log(data)
      },
      (err) => {
        console.log(err)
        this.error = err.message;
      }
    );
  }

  updatemovie(movie:Movie){
    console.log(movie)
    this.MovieService
    .update(movie)
    .subscribe(
      (data: Movie[]) => {
        this.movies = data;
        this.fillNames();
        console.log(data)
      },
      (err) => {
        console.log(err)
        this.error = err.message;
      }
    );
  }
  
    
  showDetails (movieName:string) :void{
    if (!movieName) {this.name=movieName; this.show=true;}
    else if (this.name!==movieName && this.show===false) {this.name=movieName;this.show=true}
    else if (this.name!==movieName && this.show===true) {this.name=movieName}
    else {this.show=!this.show}}

  fillNames(): void{
    this.names=[];
      this.movies.forEach((e)=>{
        this.names.push(e.name)
      })
    }
}
<div class="Home">
    <header class="Home-header">
      <span><h1>TOP 10 MOVIES</h1></span>
      <img src="../../assets/imgmovie.svg" class="App-logo" alt="logo" />
    </header>
    <div class="moviesbar">
      <div *ngIf="movies.length>0">  
          <div *ngIf="selectedCatgory"><h3> {{selectedCatgory}} movies ({{movies.length}} movies)</h3></div>    
        <div *ngFor="let movie of movies">
            <div style="color:white">{{movie.name}}</div>
            <img class="image" [src]="movie.imgurl" (click)="showDetails(movie.name)"/>     
            <div *ngIf="name===movie.name&&show">
            <div>the Category: {{movie.category}}</div>
            <div>the Grade: {{movie.grade}}</div>
            <div style="height:30px"></div>           
        </div> 
      </div>
    </div>
  
  <app-searchbar class="searchbar" (search)="getMovies($event)"></app-searchbar>
  <app-addbar class="addbar" (movieToAdd)="addmovie($event)" (movieToUpdate)="updatemovie($event)" [names]="names" [movies]="movies"></app-addbar>
  </div>

// client/React/src/components/home/home.js
import './home.css';
import Addbar from "../addbar/addbar"
import Searchbar from "../searchbar/searchbar";
import React, {useEffect, useState} from "react";
import axios from "axios";

function Home() {
const [name,setName]=useState();
const [search,setSearch]=useState();
const [movies,setMovies]=useState([]);
const [names,setNames]=useState([]);
const [show, setShow] = useState(false);
let server=process.env.REACT_APP_SERVER_ADDRESS;
 

useEffect(()=>{
// for server of dotnet:
// axios.get(server+'/Movies/Search?search='+search)

axios.get(`http://localhost:8000/Movies/Search?search = ${search}`)
// axios.get("http://localhost:8000/Movies/Search", { params: { search: search } }) // another way to same action
.then (res=>{
setMovies(res.data);
if (names.length<1){
  let theNames=[];
  res.data.forEach((m)=>theNames.push(m.name));
  setNames(theNames)}})
},[search])

const showDetails=(movie)=>{
if (!name) {setName(movie.name); setShow(true)}
else if (name!==movie.name && show===false) {setName(movie.name);setShow(true)}
else if (name!==movie.name && show===true) {setName(movie.name)}
else {setShow(!show)}}


  return (
    <div className="Home">
      <header className="Home-header">
        <span><h1>TOP 10 MOVIES</h1></span>
        <img src="imgmovie.svg" className="App-logo" alt="logo" />
      </header>
      <div className="moviesbar">
        {search&&
        <div><h3> {search} movies ({movies.length} movies)</h3></div>}    
        {movies.map((movie)=>
          <div key={movie.name}>
          <div style={{color:"white"}}>{movie.name}</div>
          <img className="image" src={movie.imgurl} onClick={()=>showDetails(movie)}/>
       
          {name===movie.name&&show&&<div>
            <div>the Category: {movie.category}</div>
            <div>the Grade: {movie.grade}</div>
            </div>}
          <div style={{height:"30px"}}></div>          
          </div>        
        )}
      </div>
      <div className="addbar" >
        <div className="addbar2">
        <Addbar movies={movies}  setMovies={setMovies} names={names} setNames={setNames}/>
        </div>      
        </div>      
      <div className="searchbar"><Searchbar  setSearch={setSearch}/></div> 
     
    </div>
    
  );
}

export default Home;
